name: seq2seq-sc
channels:
  - huggingface
  - anaconda
  - defaults
  - conda-forge
dependencies:
  - pip==22.3
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - blas=1.0=mkl
  - brotlipy=0.7.0=py39h27cfd23_1003
  - ca-certificates=2022.07.19=h06a4308_0
  - certifi=2022.9.14=py39h06a4308_0
  - cffi=1.15.1=py39h74dc2b5_0
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - click=8.0.4=py39h06a4308_0
  - cryptography=37.0.1=py39h9ce1e76_0
  - cudatoolkit=11.2.2=hbe64b41_10
  - cudnn=8.1.0.77=h90431f1_0
  - dataclasses=0.8=pyh6d0b6a4_7
  - filelock=3.6.0=pyhd3eb1b0_0
  - huggingface_hub=0.9.1=py_0
  - idna=3.3=pyhd3eb1b0_0
  - importlib-metadata=4.11.3=py39h06a4308_0
  - importlib_metadata=4.11.3=hd3eb1b0_0
  - intel-openmp=2021.4.0=h06a4308_3561
  - joblib=1.1.0=pyhd3eb1b0_0
  - ld_impl_linux-64=2.38=h1181459_1
  - libffi=3.3=he6710b0_2
  - libgcc-ng=12.1.0=h8d9b700_16
  - libgomp=12.1.0=h8d9b700_16
  - libprotobuf=3.20.1=h4ff587b_0
  - libstdcxx-ng=12.1.0=ha89aaad_16
  - mkl=2021.4.0=h06a4308_640
  - mkl-service=2.4.0=py39h7f8727e_0
  - mkl_fft=1.3.1=py39hd3c417c_0
  - mkl_random=1.2.2=py39h51133e4_0
  - ncurses=6.3=h5eee18b_3
  - numpy=1.23.1=py39h6c91a56_0
  - numpy-base=1.23.1=py39ha15fc14_0
  - openssl=1.1.1q=h7f8727e_0
  - packaging=21.3=pyhd3eb1b0_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pyopenssl=22.0.0=pyhd3eb1b0_0
  - pyparsing=3.0.9=py39h06a4308_0
  - pysocks=1.7.1=py39h06a4308_0
  - python=3.9.13=haa1d7c7_1
  - pyyaml=6.0=py39h7f8727e_1
  - readline=8.1.2=h7f8727e_1
  - regex=2022.7.9=py39h5eee18b_0
  - requests=2.28.1=py39h06a4308_0
  - sacremoses=master=py_0
  - setuptools=63.4.1=py39h06a4308_0
  - six=1.16.0=pyhd3eb1b0_1
  - sqlite=3.39.2=h5082296_0
  - tk=8.6.12=h1ccaba5_0
  - tqdm=4.64.0=py39h06a4308_0
  - transformers=4.22.1=py_0
  - typing-extensions=4.3.0=py39h06a4308_0
  - typing_extensions=4.3.0=py39h06a4308_0
  - tzdata=2022c=h04d1e81_0
  - urllib3=1.26.11=py39h06a4308_0
  - wheel=0.37.1=pyhd3eb1b0_0
  - xz=5.2.5=h7f8727e_1
  - yaml=0.2.5=h7b6447c_0
  - zipp=3.8.0=py39h06a4308_0
  - zlib=1.2.12=h5eee18b_3
  - pip:
    - absl-py==1.2.0
    - accelerate==0.13
    - aiohttp==3.8.3
    - aiosignal==1.2.0
    - astroid==2.12.10
    - astunparse==1.6.3
    - async-timeout==4.0.2
    - attrs==22.1.0
    - bert-score==0.3.12
    - cachetools==5.2.0
    - contourpy==1.0.5
    - cycler==0.11.0
    - datasets==2.5.1
    - dill==0.3.5.1
    - evaluate==0.2.2
    - flatbuffers==2.0.7
    - fonttools==4.37.3
    - frozenlist==1.3.1
    - fsspec==2022.8.2
    - gast==0.4.0
    - google-auth==2.11.1
    - google-auth-oauthlib==0.4.6
    - google-pasta==0.2.0
    - grpcio==1.48.1
    - h5py==3.7.0
    - importlib-resources==5.9.0
    - isort==5.10.1
    - keras==2.10.0
    - keras-preprocessing==1.1.2
    - kiwisolver==1.4.4
    - lazy-object-proxy==1.7.1
    - libclang==14.0.6
    - markdown==3.4.1
    - markupsafe==2.1.1
    - matplotlib==3.6.0
    - mccabe==0.7.0
    - moverscore==1.0.3
    - multidict==6.0.2
    - multiprocess==0.70.13
    - nltk==3.7
    - oauthlib==3.2.1
    - opt-einsum==3.3.0
    - pandas==1.5.0
    - pillow==9.2.0
    - platformdirs==2.5.2
    - portalocker==2.6.0
    - protobuf==3.19.5
    - psutil==5.9.2
    - pyarrow==8.0.0
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pyemd==0.5.1
    - pylint==2.15.3
    - python-dateutil==2.8.2
    - pytz==2022.2.1
    - requests-oauthlib==1.3.1
    - responses==0.18.0
    - rouge-score==0.1.2
    - rsa==4.9
    - scikit-learn==1.1.2
    - scipy==1.9.1
    - sentence-transformers==2.2.2
    - sentencepiece==0.1.97
    - sionna==0.11.0
    - tensorboard==2.10.0
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.1
    - tensorflow==2.10.0
    - tensorflow-estimator==2.10.0
    - tensorflow-io-gcs-filesystem==0.27.0
    - termcolor==2.0.1
    - threadpoolctl==3.1.0
    - tokenizers==0.12.1
    - tomli==2.0.1
    - tomlkit==0.11.4
    - torch==1.12.1
    - torchvision==0.13.1
    - typing==3.7.4.3
    - werkzeug==2.2.2
    - wrapt==1.14.1
    - xxhash==3.0.0
    - yapf==0.32.0
    - yarl==1.8.1
